In [31]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from word2number import w2n

In [32]:
d = pd.read_csv("hiring.csv")
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [33]:
d.experience = d.experience.fillna("zero")
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [34]:
d.experience = d.experience.apply(w2n.word_to_num)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [35]:
import math
median_test_score1 = d['test_score(out of 10)'].mean()
median_test_score1

7.857142857142857

In [36]:
import math
median_test_score = math.floor(d['test_score(out of 10)'].mean())
median_test_score

7

In [37]:
d['test_score(out of 10)'] = d['test_score(out of 10)'].fillna(median_test_score)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [38]:
reg = linear_model.LinearRegression()
reg.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])

LinearRegression()

In [39]:
reg.predict([[2,9,6]])

C:\Users\home\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [40]:
reg.predict([[12,10,10]])

C:\Users\home\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])

In [41]:
reg.predict([[15,8,9]])

C:\Users\home\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([95924.50256603])

In [14]:
reg.predict([[12,0,10]])

C:\Users\home\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([71534.70529062])

In [42]:
reg.predict([[0,0,10]])

C:\Users\home\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36467.47711036])

In [43]:
reg.predict([[12,0,0]])

C:\Users\home\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([50059.87962695])

In [44]:
reg.predict([[12,0,0]])

C:\Users\home\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([50059.87962695])

In [45]:
reg.predict([[0,0,0]])

C:\Users\home\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([14992.65144669])

In [46]:
withoutSal_df = pd.read_csv('hiringNOsalary.csv')
withoutSal_df

experience  test_score(out of 10)  interview_score(out of 10)
0         NaN                    8.0                         9.0
1         NaN                    8.0                         6.0
2        five                    6.0                         7.0
3         two                   10.0                        10.0
4       seven                    9.0                         6.0
5       three                    7.0                        10.0
6         ten                    NaN                         7.0
7      eleven                    7.0                         8.0
8         NaN                    5.0                         8.0
9      twelve                   12.0                        11.0
10        ten                    8.0                        10.0
11       five                    7.0                         6.0
12        six                    8.0                         NaN
13        ten                    NaN                         NaN

In [47]:
withoutSal_df.experience = withoutSal_df.experience.fillna("zero")
withoutSal_df

experience  test_score(out of 10)  interview_score(out of 10)
0        zero                    8.0                         9.0
1        zero                    8.0                         6.0
2        five                    6.0                         7.0
3         two                   10.0                        10.0
4       seven                    9.0                         6.0
5       three                    7.0                        10.0
6         ten                    NaN                         7.0
7      eleven                    7.0                         8.0
8        zero                    5.0                         8.0
9      twelve                   12.0                        11.0
10        ten                    8.0                        10.0
11       five                    7.0                         6.0
12        six                    8.0                         NaN
13        ten                    NaN                         NaN

In [48]:
withoutSal_df.experience = withoutSal_df.experience.apply(w2n.word_to_num)
withoutSal_df

experience  test_score(out of 10)  interview_score(out of 10)
0            0                    8.0                         9.0
1            0                    8.0                         6.0
2            5                    6.0                         7.0
3            2                   10.0                        10.0
4            7                    9.0                         6.0
5            3                    7.0                        10.0
6           10                    NaN                         7.0
7           11                    7.0                         8.0
8            0                    5.0                         8.0
9           12                   12.0                        11.0
10          10                    8.0                        10.0
11           5                    7.0                         6.0
12           6                    8.0                         NaN
13          10                    NaN                         NaN

In [50]:
meanData = withoutSal_df['test_score(out of 10)'].mean()
meanData

7.916666666666667

In [51]:
meanData2 = math.floor(withoutSal_df['test_score(out of 10)'].mean())
meanData2

7

In [52]:
withoutSal_df['test_score(out of 10)'] = withoutSal_df['test_score(out of 10)'].fillna(meanData2)
withoutSal_df

experience  test_score(out of 10)  interview_score(out of 10)
0            0                    8.0                         9.0
1            0                    8.0                         6.0
2            5                    6.0                         7.0
3            2                   10.0                        10.0
4            7                    9.0                         6.0
5            3                    7.0                        10.0
6           10                    7.0                         7.0
7           11                    7.0                         8.0
8            0                    5.0                         8.0
9           12                   12.0                        11.0
10          10                    8.0                        10.0
11           5                    7.0                         6.0
12           6                    8.0                         NaN
13          10                    7.0                         NaN

In [53]:
meanData3 = withoutSal_df['interview_score(out of 10)'].mean()
meanData3

8.166666666666666

In [54]:
meanData3 = math.floor(meanData3)
meanData3

8

In [ ]:
withoutSal_df

In [55]:
meanData3 = math.floor(withoutSal_df['interview_score(out of 10)'].mean())
meanData3

8

In [56]:
 withoutSal_df['interview_score(out of 10)'] =  withoutSal_df['interview_score(out of 10)'].fillna(meanData3)
withoutSal_df    

experience  test_score(out of 10)  interview_score(out of 10)
0            0                    8.0                         9.0
1            0                    8.0                         6.0
2            5                    6.0                         7.0
3            2                   10.0                        10.0
4            7                    9.0                         6.0
5            3                    7.0                        10.0
6           10                    7.0                         7.0
7           11                    7.0                         8.0
8            0                    5.0                         8.0
9           12                   12.0                        11.0
10          10                    8.0                        10.0
11           5                    7.0                         6.0
12           6                    8.0                         8.0
13          10                    7.0                         8.0

In [57]:
salaryPredicted = reg.predict(withoutSal_df)
salaryPredicted

array([ 52090.46734071,  45648.01964161,  57964.2290839 ,  64525.1061363 ,
        68325.21184635,  60783.44785255,  74796.8832586 ,  79866.63483999,
        43279.05747558, 100337.89705205,  83460.64005729,  58038.05561713,
        67476.59886447,  76944.36582496])

In [59]:
withoutSal_df['PREDICTED-SALARY'] = salaryPredicted
withoutSal_df

experience  test_score(out of 10)  interview_score(out of 10)  \
0            0                    8.0                         9.0   
1            0                    8.0                         6.0   
2            5                    6.0                         7.0   
3            2                   10.0                        10.0   
4            7                    9.0                         6.0   
5            3                    7.0                        10.0   
6           10                    7.0                         7.0   
7           11                    7.0                         8.0   
8            0                    5.0                         8.0   
9           12                   12.0                        11.0   
10          10                    8.0                        10.0   
11           5                    7.0                         6.0   
12           6                    8.0                         8.0   
13          10                    7.0                         8.0   

    PREDICTED-SALARY  
0       52090.467341  
1       45648.019642  
2       57964.229084  
3       64525.106136  
4       68325.211846  
5       60783.447853  
6       74796.883259  
7       79866.634840  
8       43279.057476  
9      100337.897052  
10      83460.640057  
11      58038.055617  
12      67476.598864  
13      76944.365825

In [60]:
withoutSal_df.to_csv('HIRING-PREDICTED-SALARY.csv')

In [61]:
hiringPredictedSal_df = pd.read_csv('HIRING-PREDICTED-SALARY.csv')
hiringPredictedSal_df

Unnamed: 0  experience  test_score(out of 10)  interview_score(out of 10)  \
0            0           0                    8.0                         9.0   
1            1           0                    8.0                         6.0   
2            2           5                    6.0                         7.0   
3            3           2                   10.0                        10.0   
4            4           7                    9.0                         6.0   
5            5           3                    7.0                        10.0   
6            6          10                    7.0                         7.0   
7            7          11                    7.0                         8.0   
8            8           0                    5.0                         8.0   
9            9          12                   12.0                        11.0   
10          10          10                    8.0                        10.0   
11          11           5                    7.0                         6.0   
12          12           6                    8.0                         8.0   
13          13          10                    7.0                         8.0   

    PREDICTED-SALARY  
0       52090.467341  
1       45648.019642  
2       57964.229084  
3       64525.106136  
4       68325.211846  
5       60783.447853  
6       74796.883259  
7       79866.634840  
8       43279.057476  
9      100337.897052  
10      83460.640057  
11      58038.055617  
12      67476.598864  
13      76944.365825