In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [4]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
df.head(3)

area   price
0  2600  550000
1  3000  565000
2  3200  610000

In [6]:
model = linear_model.LinearRegression()
model

LinearRegression()

In [7]:
model.fit(df[['area']],df.price)

LinearRegression()

In [8]:
model.coef_

array([135.78767123])

In [9]:
model.intercept_

180616.43835616432

In [10]:
model.predict([[5000]])

C:\Users\home\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [11]:
import pickle

In [12]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [13]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [14]:
mp.coef_

array([135.78767123])

In [15]:
mp.intercept_

180616.43835616432

In [16]:
mp.predict([[5000]])

C:\Users\home\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [17]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\home\AppData\Roaming\Python\Python39\site-packages\sklearn\externals\__init__.py)

In [18]:
from joblib import dump


In [19]:
dump(model,'model_joblib')

['model_joblib']

In [20]:
mj = joblib.load('model_joblib')

NameError: name 'joblib' is not defined

In [21]:
mj = dump.load('model_joblib')

AttributeError: 'function' object has no attribute 'load'

In [22]:
mj = load('model_joblib')

NameError: name 'load' is not defined

In [23]:
with open('model_joblib','rb') as f:
    mj = joblib.load(f)

NameError: name 'joblib' is not defined

In [24]:
with open('model_joblib','rb') as f:
    mj = load(f)

NameError: name 'load' is not defined

In [25]:
joblib.dump(model, 'mysaved_md_jobilb')

NameError: name 'joblib' is not defined

In [31]:
dump(model, 'mysaved_md_jobilb')

['mysaved_md_jobilb']

In [32]:
whatever = load('mysaved_md_jobilb')

NameError: name 'load' is not defined

In [26]:
import joblib as jb

In [27]:
jb.dump(model,'model_joblib2')

['model_joblib2']

In [28]:
mj2 = jb.load('model_joblib2')

In [ ]:
mj2.coe